/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as platformUsersIndexRouteImport } from './routes/(platform)/users/index'
import { Route as platformUsersUserIdRouteImport } from './routes/(platform)/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const platformUsersIndexRoute = platformUsersIndexRouteImport.update({
  id: '/(platform)/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const platformUsersUserIdRoute = platformUsersUserIdRouteImport.update({
  id: '/(platform)/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users/$userId': typeof platformUsersUserIdRoute
  '/users': typeof platformUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users/$userId': typeof platformUsersUserIdRoute
  '/users': typeof platformUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(platform)/users/$userId': typeof platformUsersUserIdRoute
  '/(platform)/users/': typeof platformUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users/$userId' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users/$userId' | '/users'
  id: '__root__' | '/' | '/(platform)/users/$userId' | '/(platform)/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  platformUsersUserIdRoute: typeof platformUsersUserIdRoute
  platformUsersIndexRoute: typeof platformUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)/users/': {
      id: '/(platform)/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof platformUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)/users/$userId': {
      id: '/(platform)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof platformUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  platformUsersUserIdRoute: platformUsersUserIdRoute,
  platformUsersIndexRoute: platformUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
